### ISSUE TITLE
nosetests --with-anyblok-bloks --failed

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/AnyBlok#39]
I'm trying to use the `--with-id` and `--failed` options of nosetests (to replay only failed tests), but it doesn't work. There seems to be a problem reading the environment variables (or more generally the configuration) during the `--failed` run.

Anyblok version: commit dcf61bab8fe36dbd31c152c6468d48dafe5a6171

To reproduce, I'm sabotaging one of the tests of anyblok_wms_base. Here's my diff
```
$ git diff
diff --git a/anyblok_wms_base/bloks/wms_core/tests/test_goods.py b/anyblok_wms_base/bloks/wms_core/tests/test_goods.py
index 23120e0..3a593d9 100644
--- a/anyblok_wms_base/bloks/wms_core/tests/test_goods.py
+++ b/anyblok_wms_base/bloks/wms_core/tests/test_goods.py
@@ -42,7 +42,7 @@ class TestGoods(BlokTestCase):
                                   reason=self.arrival, location=self.stock)
         self.assertEqual(repr(goods),
                          "Wms.Goods(id=%d, state='future', type="
-                         "Wms.Goods.Type(id=%d, code='MG'))" % (
+                         "Wms.Goods.Type(id=%d, code='MH'))" % (
                              goods.id, gt.id))
         self.assertEqual(str(goods),
                          "(id=%d, state='future', type="
```

Here's the first nose command (in the proper virtualenv, of course):

```
ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s  --with-id
```
My altered test fails as it should, and is the only one.

And here's the rerun and its outcome:

```
======================================================================
ERROR: test suite for <class 'anyblok_wms_base.bloks.wms_core.tests.test_goods.TestGoods'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<venv_path>/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "<venv_path>/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "<venv_path>/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "<venv_path>/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "<venv_path>/anyblok/anyblok/tests/testcase.py", line 333, in setUpClass
    **additional_setting)
  File "<venv_path>/anyblok/anyblok/registry.py", line 128, in get
    db_name, loadwithoutmigration=loadwithoutmigration, **kwargs)
  File "<venv_path>/anyblok/anyblok/registry.py", line 425, in __init__
    self.init_engine(db_name=db_name)
  File "<venv_path>/anyblok/anyblok/registry.py", line 466, in init_engine
    url = Configuration.get('get_url', get_url)(db_name=db_name)
  File "<venv_path>/anyblok/anyblok/config.py", line 79, in get_url
    raise ConfigurationException('No Drivername defined')
anyblok.config.ConfigurationException: No Drivername defined
-------------------- >> begin captured logging << --------------------
anyblok.config: INFO: Configuration.load_config_for_test
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```

**Comment by jssuzanne** [comment]
Can you try this:
`ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DATABASE_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s  --with-id`

**Comment by gracinet** [comment]
Ah yes I didn't notice I had shadowing of the correct environment var on that system, explaining why it didn't complain about lack of driver. I'm on another one currently, anyway.

```
$ ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DATABASE_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s --with-id
(...)
======================================================================
FAIL: test_str (anyblok_wms_base.bloks.wms_core.tests.test_goods.TestGoods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<venv_path>/anyblok_wms_base/anyblok_wms_base/bloks/wms_core/tests/test_goods.py", line 49, in test_str
    goods.id, gt.id))
AssertionError: "Wms.Goods(id=524, state='future', type=Wms.Goods.Type(id=314, code='MH'))" != "Wms.Goods(id=524, state='future', type=Wms.Goods.Type(id=314, code='MG'))"
- Wms.Goods(id=524, state='future', type=Wms.Goods.Type(id=314, code='MH'))
?                                                                      ^
+ Wms.Goods(id=524, state='future', type=Wms.Goods.Type(id=314, code='MG'))
?                                                                      ^

-------------------- >> begin captured logging << --------------------
anyblok.registry: DEBUG: [ROLLACK] with args=() and kwargs = {}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 85 tests in 8.214s

FAILED (failures=1)

$ ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DATABASE_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s --failed
ERROR

======================================================================
ERROR: test suite for <class 'anyblok_wms_base.bloks.wms_core.tests.test_goods.TestGoods'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<venv_path>/lib64/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "<venv_path>/lib64/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "<venv_path>/lib64/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "<venv_path>/lib64/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/tests/testcase.py", line 333, in setUpClass
    **additional_setting)
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/registry.py", line 128, in get
    db_name, loadwithoutmigration=loadwithoutmigration, **kwargs)
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/registry.py", line 436, in __init__
    self.load()
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/logging.py", line 92, in f
    return function(*args, **kwargs)
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/registry.py", line 952, in load
    raise e
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/registry.py", line 935, in load
    self.load_bloks(toload, False, toload)
  File "<venv_path>/lib64/python3.6/site-packages/anyblok/registry.py", line 729, in load_bloks
    "Required blok %r not found" % blok)
anyblok.registry.RegistryManagerException: Required blok 'anyblok-core' not found
-------------------- >> begin captured logging << --------------------
anyblok.config: INFO: Configuration.load_config_for_test
anyblok.registry: DEBUG: Pre assemble 'Model' entry
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('auto-orm-event = anyblok.model.event:AutoSQLAlchemyORMEventPlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('cache = anyblok.model.cache:CachePlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('event = anyblok.model.event:EventPlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('field_datetime = anyblok.model.field_datetime:AutoUpdatePlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('hybrid_method = anyblok.model.hybrid_method:HybridMethodPlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('sqla-event = anyblok.model.event:SQLAlchemyEventPlugin')
anyblok.model.plugins: INFO: AnyBlok Load model plugin: EntryPoint.parse('table_mapper = anyblok.model.table_and_mapper:TableMapperPlugin')
anyblok.registry: DEBUG: Registry.load with args (<anyblok.registry.Registry object at 0x7f836c9d03c8>,) and kwargs {}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 0 tests in 0.048s

FAILED (errors=1)
```
I'm currently working on a big refactor, for which I get a different error:

```
$ ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DATABASE_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s --with-id 
(...)
Ran 57 tests in 5.351s

FAILED (errors=18, failures=1)
$ ANYBLOK_DATABASE_NAME=test_anyblok_wms_core ANYBLOK_DATABASE_DRIVER=postgresql nosetests anyblok_wms_base/anyblok_wms_base/bloks --with-anyblok-bloks -v -s --failed
#42 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#44 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#46 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#47 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#48 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#51 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#52 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#53 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#54 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#55 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#56 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR
#57 Failure: AttributeError (type object 'Model' has no attribute 'Wms') ... ERROR

======================================================================
ERROR: Failure: AttributeError (type object 'Model' has no attribute 'Wms')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<venv_path>/lib64/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "<venv_path>/lib64/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "<venv_path>/lib64/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "<venv_path>/lib64/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<venv_path>/anyblok_wms_base/anyblok_wms_base/bloks/wms_core/operation/__init__.py", line 11, in <module>
    from . import base
  File "<venv_path>/anyblok_wms_base/anyblok_wms_base/bloks/wms_core/operation/base.py", line 32, in <module>
    @register(Model.Wms)
AttributeError: type object 'Model' has no attribute 'Wms'

(...) Repetitions of the same tracebacks (...)
----------------------------------------------------------------------
Ran 12 tests in 0.009s

FAILED (errors=12)
```

**Comment by jssuzanne** [comment]
because the plugin nose don't read the system config file. I think it had to read it

**Comment by jssuzanne** [comment]
The global system config file is already loaded. It is another issue

**Comment by gracinet** [comment]
Final summary for this issue…
One has to choose between
- correct coverage report: use the plugin
- advanced tests selection: use anyblok_nose

It short, the reason is that the plugin can't prevent nose from importing a testcase which would itself import AnyBlok before the Registry is setup, and that happens if one specifies the target test too specifically (as in with --failed)

This is covered in the freshly written doc section about testing practices: http://anyblok.readthedocs.io/en/latest/basic_usage.html#writing-and-launching-tests, and I'm therefore closing this issue
