### ISSUE TITLE
nose plugin called too late if first entry in directory is a package

### ISSUE THREAD

**Issue by gracinet** [AnyBlok/AnyBlok#47]
(see workaround at the end, and I hope to be able to fix this)

While discovering tests to run, nose will walk the directory hierarchy. In each directory, it sorts the directory entries and performs different actions in order for files and directories.

I'll explain by commenting the code of `nose.loader` I have in my virtual environment:

```
    def loadTestsFromDir(self, path):
        """Load tests from the directory at path. This is a generator
        -- each suite of tests from a module or other file is yielded
        and is expected to be executed before the next file is
        examined.
        """
        log.debug("load from dir %s", path)
        plugins = self.config.plugins
        plugins.beforeDirectory(path)
        if self.config.addPaths:
            paths_added = add_path(path, self.config)

        entries = os.listdir(path)
        sort_list(entries, regex_last_key(self.config.testMatch))
        for entry in entries:
            # this hard-coded initial-dot test will be removed:
            # http://code.google.com/p/python-nose/issues/detail?id=82
            if entry.startswith('.'):
                continue
            entry_path = op_abspath(op_join(path, entry))
            is_file = op_isfile(entry_path)
            wanted = False
            if is_file:
                is_dir = False
                wanted = self.selector.wantFile(entry_path)
```
Here ``self.selector.wantFile`` calls Anyblok's Nose plugin own `wantFile()` method, which initializes the registry

```
            else:
                is_dir = op_isdir(entry_path)
                if is_dir:
                    # this hard-coded initial-underscore test will be removed:
                    # http://code.google.com/p/python-nose/issues/detail?id=82
                    if entry.startswith('_'):
                        continue
                    wanted = self.selector.wantDirectory(entry_path)
```
`self.selector.wantDirectory` does not seem to call Anyblok Nose Plugin

```
            is_package = ispackage(entry_path)

            # Python 3.3 now implements PEP 420: Implicit Namespace Packages.
            # As a result, it's now possible that parent paths that have a
            # segment with the same basename as our package ends up
            # in module.__path__.  So we have to keep track of what we've
            # visited, and not-revisit them again.
            if wanted and not self._haveVisited(entry_path):
                self._addVisitedPath(entry_path)
                if is_file:
                    plugins.beforeContext()
                    if entry.endswith('.py'):
                        yield self.loadTestsFromName(
                            entry_path, discovered=True)
                    else:
                        yield self.loadTestsFromFile(entry_path)
                    plugins.afterContext()
                elif is_package:
                    # Load the entry as a package: given the full path,
                    # loadTestsFromName() will figure it out
                    yield self.loadTestsFromName(
                        entry_path, discovered=True)
```
And here, if this is called before any regular file has been seen by the loop, we get a direct import before the registry has been initialized, and that's usually an error

For instance, in the current master of anyblok_wms_base, the sorted [listing of wms_core](https://github.com/AnyBlok/anyblok_wms_base/tree/a38f924/anyblok_wms_base/bloks/wms_core) has `goods.py` and `location.py` before the `operation` package (`__init__.py` is discarded, since it starts with an underscore) : the tests pass, but actually, it's lucky.

If I split however `goods.py` in a package called `goods` (say, with submodules `goods`, and `type`), then `goods` is the first entry not starting with an underscore in the directory listing of `wms_core`. It's a package, and I get this error:

```

======================================================================
ERROR: Failure: AttributeError (type object 'Model' has no attribute 'Wms')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anyblok_wms/lib64/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "anyblok_wms/lib64/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "anyblok_wms/lib64/python3.6/site-packages/nose/importer.py", line 48, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "anyblok_wms/lib64/python3.6/site-packages/nose/importer.py", line 95, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "anyblok_wms/anyblok_wms_base/anyblok_wms_base/bloks/wms_core/goods/__init__.py", line 10, in <module>
    from . import goods
  File "anyblok_wms/anyblok_wms_base/anyblok_wms_base/bloks/wms_core/goods/goods.py", line 32, in <module>
    @register(Model.Wms)
AttributeError: type object 'Model' has no attribute 'Wms'
```
And that's because the `Wms` declaration has indeed not been imported. Of course if the registry had been loaded by Anyblok Nose plugin, we wouldn't have this problem.

Workaround:  putting a regular file named `aaa` in that same directory works

(I'll check if implementing `wantDirectory` would solve this issue for good)

**Comment by jssuzanne** [comment]
Can we close this issue ?

**Comment by gracinet** [comment]
Yes, thank your for releasing this. The following build proves it works over the released version: https://travis-ci.org/AnyBlok/anyblok_wms_base
